version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: deps
    command: pnpm dev --host 0.0.0.0 --port 5173
    ports:
      - '5173:5173'
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
    depends_on:
      - api
      - redis

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: deps
    command: pnpm dev
    ports:
      - '3000:3000'
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
      INTERNAL_TOKEN: ${INTERNAL_TOKEN:-dev-internal}
    depends_on:
      - redis
    volumes:
      - api-data:/usr/src/app/data

  playtester:
    build:
      context: .
      dockerfile: services/playtester/Dockerfile
      target: deps
    command: pnpm dev
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4.1-mini}
      GEN_MAX_ATTEMPTS: ${GEN_MAX_ATTEMPTS:-3}
      GEN_SIMHASH_TTL_SEC: ${GEN_SIMHASH_TTL_SEC:-604800}
      OPENAI_REQ_TIMEOUT_MS: ${OPENAI_REQ_TIMEOUT_MS:-20000}
      API_BASE_URL: http://api:3000
      INTERNAL_TOKEN: ${INTERNAL_TOKEN:-dev-internal}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  api-data:
