version: '3.9'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: pnpm dev --host 0.0.0.0 --port 5173
    ports:
      - '5173:5173'
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
    depends_on:
      - api
      - redis

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: pnpm dev
    ports:
      - '3000:3000'
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  playtester:
    build:
      context: ./services/playtester
      dockerfile: Dockerfile
    command: pnpm dev
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
