openapi: 3.1.0
info:
  title: Infinite Runner API
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /levels/generate:
    post:
      summary: Queue a single level generation job
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '202':
          description: Job accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
        '429':
          description: Rate limited
  /levels/generate-batch:
    post:
      summary: Queue a batch of level generation jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchGenerateRequest'
      responses:
        '202':
          description: Batch accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchGenerateResponse'
        '200':
          description: Idempotent replay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchGenerateResponse'
        '400':
          description: Validation error
        '409':
          description: Idempotency conflict
        '429':
          description: Rate limited
  /batches/{id}:
    get:
      summary: Inspect a batch and its jobs
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Batch detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchDetailResponse'
        '404':
          description: Batch not found
  /batches:
    get:
      summary: List batches with metrics
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
        - in: query
          name: cursor
          schema:
            type: integer
      responses:
        '200':
          description: Batch list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchListResponse'
components:
  schemas:
    Ability:
      type: object
      required:
        - run
        - jump
      properties:
        run:
          type: boolean
          const: true
        jump:
          type: boolean
          const: true
        highJump:
          type: boolean
        shortFly:
          type: boolean
        jetpack:
          type: object
          properties:
            fuel:
              type: integer
              minimum: 0
            thrust:
              type: number
              minimum: 0
    GenerateRequest:
      type: object
      properties:
        seed:
          type: string
        difficulty:
          type: integer
          minimum: 1
        abilities:
          $ref: '#/components/schemas/Ability'
    GenerateResponse:
      type: object
      required:
        - job_id
      properties:
        job_id:
          type: string
    BatchGenerateRequest:
      type: object
      required:
        - count
      properties:
        count:
          type: integer
          minimum: 1
          maximum: 1000
        start_level:
          type: integer
          minimum: 1
        seed_prefix:
          type: string
        season:
          type: string
        difficulty_mode:
          type: string
          enum: [fixed, ramp]
          default: fixed
        difficulty_fixed:
          type: integer
          minimum: 1
        difficulty_ramp:
          type: object
          properties:
            from:
              type: integer
              minimum: 1
            to:
              type: integer
              minimum: 1
            steps:
              oneOf:
                - type: string
                  enum: [auto]
                - type: integer
                  minimum: 2
        abilities:
          $ref: '#/components/schemas/Ability'
        constraints:
          type: object
          properties:
            max_moving_platforms:
              type: integer
              minimum: 0
            max_enemies:
              type: integer
              minimum: 0
            max_hazards:
              type: integer
              minimum: 0
        idempotency_key:
          type: string
    BatchGenerateResponse:
      type: object
      required:
        - batch_id
        - job_ids
        - count
      properties:
        batch_id:
          type: string
        job_ids:
          type: array
          items:
            type: string
        count:
          type: integer
    BatchJob:
      type: object
      required:
        - job_id
        - status
      properties:
        job_id:
          type: string
        status:
          type: string
          enum: [queued, running, succeeded, failed, canceled]
        level_id:
          type: string
          nullable: true
        error:
          type: string
          nullable: true
    BatchMetrics:
      type: object
      required:
        - total
        - queued
        - running
        - succeeded
        - failed
        - canceled
      properties:
        total:
          type: integer
        queued:
          type: integer
        running:
          type: integer
        succeeded:
          type: integer
        failed:
          type: integer
        canceled:
          type: integer
        avg_duration_ms:
          type: integer
          nullable: true
        p95_duration_ms:
          type: integer
          nullable: true
    BatchDetailResponse:
      type: object
      required:
        - batch_id
        - status
        - metrics
        - jobs
        - levels
        - errors
      properties:
        batch_id:
          type: string
        status:
          type: string
          enum: [queued, running, partial, succeeded, failed, canceled]
        created_at:
          type: integer
        updated_at:
          type: integer
        request:
          type: object
          nullable: true
        metrics:
          $ref: '#/components/schemas/BatchMetrics'
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/BatchJob'
        levels:
          type: array
          items:
            type: string
        errors:
          type: array
          items:
            type: object
            required: [job_id, message]
            properties:
              job_id:
                type: string
              message:
                type: string
    BatchListEntry:
      type: object
      required:
        - batch_id
        - status
        - requested_count
        - metrics
      properties:
        batch_id:
          type: string
        status:
          type: string
        created_at:
          type: integer
        updated_at:
          type: integer
        requested_count:
          type: integer
        request:
          type: object
          nullable: true
        metrics:
          $ref: '#/components/schemas/BatchMetrics'
    BatchListResponse:
      type: object
      required:
        - batches
        - next_cursor
      properties:
        batches:
          type: array
          items:
            $ref: '#/components/schemas/BatchListEntry'
        next_cursor:
          type: integer
          nullable: true
